_target_: lightning.pytorch.trainer.Trainer

# Default path for logs and weights when no logger or ModelCheckpoint callback passed
default_root_dir: ${paths.output_dir}

# min/max number of trainig steps/epochs (mostly defined in experiments)
max_epochs: 10

# might be useful for SLURM jobs ?
# max_time: null

accelerator: cpu
devices: 1

# mixed precision for extra speed-up (default to 32)
# precision: 16

# how often to log (does not write to disk). (Default: 50)
log_every_n_steps: 50

# Enable anomaly detection for the autograd engine
detect_anomaly: False

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# if speedup is needed without deterministic results
# benchmark: True