# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - _self_ 

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/eval/${synth.name}/${model.name}
sweep:
  dir: ${paths.log_dir}/eval/${synth.name}/${model.name}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log