# enter the path to the pkl dataset folder for the MMR validation
path: ${paths.root_dir}/data/datasets/diva_mn04_size=65536_seed=400_hpo_val_v1

loader:
  num_ranks: 512 # dataloader batch size corresponds to the number ranking evaluation to compute the mean from (the resulting number of samples per evaluation is thus dataset_size // num_ranks)
  num_workers: 8
  shuffle: False # always use the same targets
  pin_memory: False
  drop_last: True

name: diva_mn04_hpo_val_v1