# enter the path to the pkl dataset folder for the MMR validation
path: ${paths.root_dir}/data/datasets/talnm_mn04_size=131072_seed=401_val_v1

loader:
  # dataloader batch size corresponds to the number ranking evaluation to compute 
  # the mean from (the resulting number of samples per evaluation is thus dataset_size // num_ranks)
  num_ranks: 512 # TODO: change to 256 
  num_workers: 8
  shuffle: False # always use the same targets
  pin_memory: False
  drop_last: True

name: talnm_mn04_val_v1