cfg:
  _target_: models.preset.highway_ft
  hidden_features: 896
  num_blocks: 6
  block_kwargs: 
    norm: BatchNorm1d
    act_fn: ReLU
    dropout_p: 0.0
  embedding_kwargs:
    embedding_dim: 32
    pe_dropout_p: 0.0

name: highway_ft