cfg:
  _target_: models.preset.mlp_raw
  # out_features: passed by the audio model at runtime
  hidden_features: 1024
  num_blocks: 2
  block_kwargs: 
    norm: LayerNorm
    act_fn: GELU
    dropout_p: 0.0

name: mlp_gelu_raw