cfg:
  _target_: models.preset.mlp_raw
  # out_features: passed by the audio model at runtime
  hidden_features: 1536
  num_blocks: 2
  block_kwargs: 
    norm: BatchNorm1d
    act_fn: ReLU
    dropout_p: 0.0

name: mlp_relu_raw