# @package _global_

defaults:
  - override /search_space: resnet

m_preset:
  cfg:
    _target_: models.preset.resnet_oh
    # hidden_features: 1024 # passes at runtime by optuna
    # num_blocks: 2 # passes at runtime by optuna
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0
      residual_dropout_p: 0.0
  
  name: resnet_oh