# @package _global_
 
defaults:
  - _self_
  - dataset: tal_noisemaker_mn04_v1
  - model: ??? 
  - hydra: default
  - logger: null 
  - paths: default 

# task name, determines output directory path
task_name: eval

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: 
  - ${task_name}
  - ${test_dataset.name}
  - ${model.name}
  - ${ckpt_name}


# provide checkpoint filename (which should be in PROJECT_ROOT/checkpoints) 

ckpt_path: ${paths.ckpt_dir}/${model.ckpt_name}

# seed for random number generators in pytorch, numpy and python.random
seed: 42