# @package _global_

defaults:
  - _self_
  - synth: talnm
  - model: ??? 
  - hydra: default
  - logger: null 
  - paths: default 

# task name, determines output directory path
task_name: eval

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python eval.py tags="[first_tag, second_tag]"`
tags: 
  - ${task_name}
  - ${synth.name}
  - ${model.name}


# ckpt_path to be set automatically by the model cfg
ckpt_path: ${model.ckpt_path}

# seed for random number generators in pytorch, numpy and python.random
seed: 42