# @package _global_

defaults:
  - _self_
  - synth: talnm
  - model: diva_highway_ft_b
  - hydra: default
  - wandb: default 
  - paths: default 

# task name determines output directory path (overwritten in model cfg)
task_name: ""

tags: 
  - ${synth.name}
  - ${model.type}
  - ${model.size}

ckpt_path: ${paths.ckpt_dir}/${model.ckpt_name}

# seed for random number generators in pytorch, numpy and python.random
seed: 42