############ Export path Settings
# Path relative to the project root where the dataset will be exported
export_relative_path: div_check/data

# tag to be appended to the generated folder (must be provided by the user)
tag: ???

############ Data generation settings

### PresetHelper settings
# synthesizer used to generate the dataset
synth: tal_noisemaker

# synthesizer parameters to exclude when generating presets
parameters_to_exclude_str: 
  - master_volume
  - voices
  - lfo_1_sync
  - lfo_1_keytrigger
  - lfo_2_sync
  - lfo_2_keytrigger
  - envelope*
  - portamento*
  - pitchwheel*
  - delay*

### SynthDataset settings
# dataset size:
# need to be num_eval * num_preds_per_eval for MRR validation dataset
# e.g., for 128 evaluations and 512 predictions per eval
# we have 128 * 512 = 64_512 samples
dataset_size: 65_536
# the following are used to instantiate a SynthDataset object (see implementation for details)
seed_offset: 45_858
render_duration_in_sec: 5.0
midi_note: 60
midi_velocity: 100
midi_duration_in_sec: 2.0

# batch size used to generate the dataset (will not be stored)
batch_size: 128

# can be useful to check the target audio for the MRR evaluation since those are taken from the first batch
export_audio: False

############ Audio model settings
# pre-trained audio model used as feature extractor to generate the labels
audio_fe: mn04

############ Hydra stuff
# disable output directory
root_dir: ${oc.env:PROJECT_ROOT}

hydra:
  output_subdir: null
  run:
    dir: ${root_dir}/${export_relative_path}/${synth}_${audio_fe}_size=${dataset_size}_seed=${seed_offset}_pkl_${tag}

  job: 
    chdir: True

  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/configs.log
    formatters:
      simple:
        format: '%(message)s'
