# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html 

# keep k-top on train loss (L1)

ckpt_last:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints # directory to save the model file
  filename: ${m_preset.name}_${train_dataset.name}_last
  auto_insert_metric_name: False # when True, the checkpoints filenames will contain the metric name
  every_n_epochs: 1 # number of epochs between checkpoints
  save_on_train_epoch_end: True # run checkpointing at the end of the training epoch