# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

# the following callback allows to save a model checkpoint every N training steps
# but only keeping the last one (only for those created by THIS ModelCheckpoint callback)
# it is mostly done for backup purpose or resuming training

model_checkpoint_step:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints # directory to save the model file
  filename: ${m_preset.name}_${m_audio.name}_${dataset_train.name}_s{step}
  auto_insert_metric_name: False # when True, the checkpoints filenames will contain the metric name

  every_n_train_steps: 100 # number of training steps between checkpoints