# @package _global_

defaults:
  - override /synth: talnm

model: 
  cfg: 
    _target_: models.preset.mlp_oh
    hidden_features: 2048
    num_blocks: 1
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: mlp_oh
  val_mrr: TODO
  val_loss: TODO
  epoch: TODO
  num_train_epochs: 29

  ckpt_name: ${synth.name}_${model.type}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_mrr