# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 8_414_125 parameters
    _target_: models.preset.highway_ft
    hidden_features: 512
    num_blocks: 6
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0
    embedding_kwargs:
      token_dim: 64
      pe_dropout_p: 0.0
  
  type: highway_ft
  size: b
  val_mrr: 0.7551
  epoch: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}

# TO ADD:
# X synth
# X model_type
# X model_size
# X num_params
# X val_mrr
# X epoch
# X ckpt_name
# X l1 loss (hc)
# X l1 loss (rnd)
# X mrr (hc)
# X mrr (rnd)
# X top-k (hc)
# X top-k (rnd)

# - top10 worst predictions
# - FLOPS and other metrics