cfg: # 8_307_904 parameters
  _target_: models.preset.highway_oh
  hidden_features: 896
  num_blocks: 6
  block_kwargs: 
    norm: BatchNorm1d
    act_fn: ReLU
    dropout_p: 0.0

name: diva_highway_oh_b_0.25

ckpt_path: ${paths.log_dir}/highway_oh/diva_mn04_train_v1/diva_highway_oh_b_0.25/checkpoints/highway_oh_diva_mn04_train_v1_e13_mrr0.6706.ckpt