# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 6_360_749 parameters
    _target_: models.preset.highway_oh
    hidden_features: 768
    num_blocks: 6
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0

task_name: diva_highway_oh_b

ckpt_path: ${paths.ckpt_dir}/diva_highway_oh_b_e9_mrr0.7984.ckpt