# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 15_302_829 parameters
    _target_: models.preset.highway_oh
    hidden_features: 1024
    num_blocks: 8
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0

task_name: diva_highway_oh_l

ckpt_path: ${paths.ckpt_dir}/diva_highway_oh_l_e8_mrr0.8104.ckpt