# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: 
    _target_: models.preset.highway_oh
    hidden_features: 768
    num_blocks: 6
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: highway_oh
  size: b
  val_mrr: 0.7984
  epoch: 9
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}