# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 5_400_749 parameters
    _target_: models.preset.mlp_oh
    hidden_features: 2048
    num_blocks: 1
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0

task_name: diva_mlp_oh_b

ckpt_path: ${paths.ckpt_dir}/diva_mlp_oh_b_e9_mrr0.5478.ckpt