# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 3_301_293 parameters
    _target_: models.preset.highway_ft
    hidden_features: 256
    num_blocks: 4
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0
    embedding_kwargs:
      token_dim: 64
      pe_dropout_p: 0.0

task_name: diva_highway_ft_s

ckpt_path: ${paths.ckpt_dir}/diva_highway_ft_s_e8_mrr0.6352.ckpt