# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: # 11_246_765 parameters
    _target_: models.preset.mlp_oh
    hidden_features: 3072
    num_blocks: 1 
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: mlp_oh
  size: l
  val_mrr: 0.5286
  epoch: 8
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}