# @package _global_

defaults:
  - override /synth: diva

model: 
  cfg: 
    _target_: models.preset.tfm
    pe_type: absolute
    hidden_features: 256
    num_blocks: 6
    num_heads: 8
    mlp_factor: 4.0
    pooling_type: cls
    last_activation: ReLU
    pe_dropout_p: 0.0
    block_activation: relu
    block_dropout_p: 0.0

  type: tfm
  size: b
  val_mrr: 0.8641
  epoch: 9
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}