cfg:
  _target_: models.preset.mlp_relu_oh
  hidden_features: 3072 
  num_blocks: 2
  block_kwargs: 
    dropout_p: 0.0

name: mlp_relu_oh

# ckpt_name: mlp_relu_oh_talnm_mn04_train-v1_e4_mrr0.9812.ckpt # best val loss
ckpt_name: mlp_relu_oh_talnm_mn04_train-v1_e4_l0.0550.ckpt # best train loss