# @package _global_

defaults:
  - override /synth: talnm

model:
  cfg: # 16_937_901 parameters
    _target_: models.preset.highway_ft
    hidden_features: 768
    num_blocks: 8
    token_dim: 64
    pe_dropout_p: 0.0
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: highway_ft
  size: l
  val_mrr: 0.9751
  epoch: 9
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}