# @package _global_

defaults:
  - override /synth: talnm

model:
  cfg: # 16_937_901 parameters
    _target_: models.preset.highway_ft
    hidden_features: 768
    num_blocks: 8
    block_kwargs: 
      norm: BatchNorm1d
      act_fn: ReLU
      dropout_p: 0.0
    embedding_kwargs:
      token_dim: 64
      pe_dropout_p: 0.0

task_name: talnm_highway_ft_l

ckpt_path: ${paths.ckpt_dir}/talnm_highway_ft_l_e9_mrr0.9751.ckpt