# @package _global_

defaults:
  - override /synth: talnm

model:
  cfg: 
    _target_: models.preset.highway_ft
    hidden_features: 512
    num_blocks: 6
    token_dim: 64
    pe_dropout_p: 0.0
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: highway_ft
  val_mrr: 0.9808
  val_loss: 0.0550
  epoch: 29
  num_train_epochs: 29

  ckpt_name: ${synth.name}_${model.type}_e${model.epoch}_loss0.0550.ckpt

task_name: ${synth.name}_${model.type}