cfg: # 1_656_000 parameters
  _target_: models.preset.tfm
  pe_type: absolute
  hidden_features: 256
  num_blocks: 2
  num_heads: 8
  mlp_factor: 4
  pooling_type: cls
  last_activation: ReLU
  tokenizer_kwargs:
    pe_dropout_p: 0.0
  block_kwargs: 
    activation: relu
    dropout: 0.0

name: talnm_tfm_s_e6_mrr0.9815

ckpt_path: ${paths.log_dir}/tfm/talnm_mn04_train_v1/talnm_tfm_s_bs512/checkpoints/talnm_tfm_s_bs512_e6_mrr0.9815.ckpt