# @package _global_

defaults:
  - override /synth: talnm

model:
  cfg: # 1_384_443 parameters
    _target_: models.preset.highway_ft
    hidden_features: 256
    num_blocks: 4
    token_dim: 64
    pe_dropout_p: 0.0
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: highway_ft
  size: s
  val_mrr: 0.9593
  epoch: 8
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}