# @package _global_

defaults:
  - override /synth: talnm

model:
  cfg: # 6_035_771 parameters
    _target_: models.preset.highway_oh
    hidden_features: 1024
    num_blocks: 8
    block_norm: BatchNorm1d
    block_act_fn: ReLU
    block_dropout_p: 0.0

  type: highway_oh
  size: l
  val_mrr: 0.9824
  epoch: 9
  num_train_epochs: 9

  ckpt_name: ${synth.name}_${model.type}_${model.size}_e${model.epoch}_mrr${model.val_mrr}.ckpt

task_name: ${synth.name}_${model.type}_${model.size}