cfg:
  _target_: data.datasets.SynthDataset
  dataset_size: ??? # depends on base_{iter, epoch} experiments
  seed_offset: ??? # depends on base_{iter, epoch} experiments
  render_duration_in_sec: 5
  midi_note: 60
  midi_velocity: 100
  midi_duration_in_sec: 2

name: yo