defaults:
  - base

cfg:
  preset_helper:
    _target_: utils.synth.PresetHelper
    synth_name: tal_noisemaker
    params_to_exclude_str: 
      - master_volume
      - voices
      - lfo_1_sync
      - lfo_1_keytrigger
      - lfo_2_sync
      - lfo_2_keytrigger
      - envelope*
      - portamento*
      - pitchwheel*
      - delay*

name: ${.cfg.preset_helper.synth_name}