# path to the pkl dataset folder used for training
path: ${paths.root_dir}/data/datasets/tal_noisemaker_mn04_size=10240000_seed=500_pkl_train-v1

loader:
  batch_size: 512
  num_workers: 8
  shuffle: True
  pin_memory: False
  drop_last: False

name: tal_noisemaker_mn04_train-v1