##### Architecture HPs
# number of blocks for the preset encoder
num_blocks: 2

# number of hidden features for the preset encoder
hidden_features: 1536


##### scheduler HPs
# switch from constant to cosine decay
milestone:
  type: int
  kwargs:
    name: milestone
    low: 0
    high: 1500

# starting learning rate
base_lr: 
  type: float
  kwargs:
    name: base_lr
    low: 0.0001
    high: 0.01
    log: true

# scheduler final lr
min_lr:
  type: float
  kwargs:
    name: min_lr
    low: 0.0000000001
    high: 0.01
    log: true


##### Adam HPs
# Exp decay rate for 1st moment estimate
beta1:
  type: float
  kwargs:
    name: beta1
    low: 0.8
    high: 0.999
    step: 0.001

# Exp decay rate for 1st moment estimate
beta2:
  type: float
  kwargs:
    name: beta2
    low: 0.90
    high: 0.999
    step: 0.001

# epsilon for numerical stability
eps:
  type: float
  kwargs:
    name: eps
    low: 0.0000000001
    high: 0.0001
    log: true



